version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "5:00"
    labels:
      - "dependency"
    assignees:
      - "cdce8p"
    open-pull-requests-limit: 10
    rebase-strategy: "disabled"
    # Always use only the latest version
    versioning-strategy: increase

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "5:00"
    labels:
      - "dependency"
    assignees:
      - "cdce8p"
    open-pull-requests-limit: 10
    rebase-strategy: "disabled"
