-   id: python-typing-update
    name: Update Python typing
    description: Update Python typing syntax
    entry: python-typing-update
    require_serial: true
    language: python
    types: [python]
    minimum_pre_commit_version: 0.15.0
